# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20160615_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
