# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-16 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160615_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_type',
            field=models.CharField(default='Gerais', max_length=50),
        ),
    ]
