# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='approved_comment',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.TextField(default='Escreva seu comentário aqui!'),
        ),
    ]
