# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20160702_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
